### PR TITLE
drm: don't schedule new frame events on disabled outputs

### PR DESCRIPTION
**Pull request by vaxerski**
Fixes https://github.com/hyprwm/Hyprland/issues/6459

Needs a test run

### CODE REVIEW

**Comment by gulafaran** [comment]
dpms works with your patch but my cpu goes ragemode still. something like this seems to work better

```
diff --git a/src/backend/drm/DRM.cpp b/src/backend/drm/DRM.cpp
index 8ec9c30..5bbd94c 100644
--- a/src/backend/drm/DRM.cpp
+++ b/src/backend/drm/DRM.cpp
@@ -806,6 +806,9 @@ static void handlePF(int fd, unsigned seq, unsigned tv_sec, unsigned tv_usec, un
         return;
     }
 
+    if (!pageFlip->connector->output->state->state().enabled || !BACKEND->sessionActive())
+        return;
+
     pageFlip->connector->onPresent();
 
     uint32_t flags = IOutput::AQ_OUTPUT_PRESENT_VSYNC | IOutput::AQ_OUTPUT_PRESENT_HW_CLOCK | IOutput::AQ_OUTPUT_PRESENT_HW_COMPLETION | IOutput::AQ_OUTPUT_PRESENT_ZEROCOPY;
@@ -820,7 +823,7 @@ static void handlePF(int fd, unsigned seq, unsigned tv_sec, unsigned tv_usec, un
         .flags     = flags,
     });
 
-    if (BACKEND->sessionActive() && !pageFlip->connector->frameEventScheduled)
+    if (!pageFlip->connector->frameEventScheduled)
         pageFlip->connector->output->events.frame.emit();
 }
 
```

probably dont want to call onPresent and emit present event on output in dpms and session not active. no idea about the memleak

**Comment by gulafaran** [comment]
> dpms works with your patch but my cpu goes ragemode still. something like this seems to work better
> 
> ```
> diff --git a/src/backend/drm/DRM.cpp b/src/backend/drm/DRM.cpp
> index 8ec9c30..5bbd94c 100644
> --- a/src/backend/drm/DRM.cpp
> +++ b/src/backend/drm/DRM.cpp
> @@ -806,6 +806,9 @@ static void handlePF(int fd, unsigned seq, unsigned tv_sec, unsigned tv_usec, un
>          return;
>      }
>  
> +    if (!pageFlip->connector->output->state->state().enabled || !BACKEND->sessionActive())
> +        return;
> +
>      pageFlip->connector->onPresent();
>  
>      uint32_t flags = IOutput::AQ_OUTPUT_PRESENT_VSYNC | IOutput::AQ_OUTPUT_PRESENT_HW_CLOCK | IOutput::AQ_OUTPUT_PRESENT_HW_COMPLETION | IOutput::AQ_OUTPUT_PRESENT_ZEROCOPY;
> @@ -820,7 +823,7 @@ static void handlePF(int fd, unsigned seq, unsigned tv_sec, unsigned tv_usec, un
>          .flags     = flags,
>      });
>  
> -    if (BACKEND->sessionActive() && !pageFlip->connector->frameEventScheduled)
> +    if (!pageFlip->connector->frameEventScheduled)
>          pageFlip->connector->output->events.frame.emit();
>  }
>  
> ```
> 
> probably dont want to call onPresent and emit present event on output in dpms and session not active. no idea about the memleak

Nvm cpu rages randomly still on dpms

**Comment by sp0nks** [comment]
Dpms off switches off both of my screens off, but CPU goes up and it seems like the memory creep is back.
Will have to do more testing to confirm memory leak.

**Comment by gulafaran** [comment]
now we are talking, no more cpu rampage.

```
diff --git a/src/backend/drm/DRM.cpp b/src/backend/drm/DRM.cpp
index 8ec9c30..78b61a8 100644
--- a/src/backend/drm/DRM.cpp
+++ b/src/backend/drm/DRM.cpp
@@ -806,6 +806,9 @@ static void handlePF(int fd, unsigned seq, unsigned tv_sec, unsigned tv_usec, un
         return;
     }
 
+    if (!pageFlip->connector->output->state->state().enabled)
+        return;
+
     pageFlip->connector->onPresent();
 
     uint32_t flags = IOutput::AQ_OUTPUT_PRESENT_VSYNC | IOutput::AQ_OUTPUT_PRESENT_HW_CLOCK | IOutput::AQ_OUTPUT_PRESENT_HW_COMPLETION | IOutput::AQ_OUTPUT_PRESENT_ZEROCOPY;
@@ -820,11 +823,14 @@ static void handlePF(int fd, unsigned seq, unsigned tv_sec, unsigned tv_usec, un
         .flags     = flags,
     });
 
-    if (BACKEND->sessionActive() && !pageFlip->connector->frameEventScheduled)
+    if (!pageFlip->connector->frameEventScheduled)
         pageFlip->connector->output->events.frame.emit();
 }
 
 bool Aquamarine::CDRMBackend::dispatchEvents() {
+    if (!sessionActive())
+        return true;
+
     drmEventContext event = {
         .version            = 3,
         .page_flip_handler2 = ::handlePF,
@@ -1711,7 +1717,7 @@ Aquamarine::CDRMOutput::CDRMOutput(const std::string& name_, Hyprutils::Memory::
 
     frameIdle = makeShared<std::function<void(void)>>([this]() {
         connector->frameEventScheduled = false;
-        if (connector->isPageFlipPending)
+        if (connector->isPageFlipPending || !backend->sessionActive())
             return;
         events.frame.emit();
     });
```

and dpms still works.

**Comment by gulafaran** [comment]
> now we are talking, no more cpu rampage.
> 
> ```
> diff --git a/src/backend/drm/DRM.cpp b/src/backend/drm/DRM.cpp
> index 8ec9c30..78b61a8 100644
> --- a/src/backend/drm/DRM.cpp
> +++ b/src/backend/drm/DRM.cpp
> @@ -806,6 +806,9 @@ static void handlePF(int fd, unsigned seq, unsigned tv_sec, unsigned tv_usec, un
>          return;
>      }
>  
> +    if (!pageFlip->connector->output->state->state().enabled)
> +        return;
> +
>      pageFlip->connector->onPresent();
>  
>      uint32_t flags = IOutput::AQ_OUTPUT_PRESENT_VSYNC | IOutput::AQ_OUTPUT_PRESENT_HW_CLOCK | IOutput::AQ_OUTPUT_PRESENT_HW_COMPLETION | IOutput::AQ_OUTPUT_PRESENT_ZEROCOPY;
> @@ -820,11 +823,14 @@ static void handlePF(int fd, unsigned seq, unsigned tv_sec, unsigned tv_usec, un
>          .flags     = flags,
>      });
>  
> -    if (BACKEND->sessionActive() && !pageFlip->connector->frameEventScheduled)
> +    if (!pageFlip->connector->frameEventScheduled)
>          pageFlip->connector->output->events.frame.emit();
>  }
>  
>  bool Aquamarine::CDRMBackend::dispatchEvents() {
> +    if (!sessionActive())
> +        return true;
> +
>      drmEventContext event = {
>          .version            = 3,
>          .page_flip_handler2 = ::handlePF,
> @@ -1711,7 +1717,7 @@ Aquamarine::CDRMOutput::CDRMOutput(const std::string& name_, Hyprutils::Memory::
>  
>      frameIdle = makeShared<std::function<void(void)>>([this]() {
>          connector->frameEventScheduled = false;
> -        if (connector->isPageFlipPending)
> +        if (connector->isPageFlipPending || !backend->sessionActive())
>              return;
>          events.frame.emit();
>      });
> ```
> 
> and dpms still works.

and after like 15+ dpms on/off it rages again..

**Comment by sp0nks** [comment]
Mine doesn't rage, but it does go up while dpms off.
I see some increase in memory usage with each dpms off as well.

**Comment by vaxerski** [comment]
try now

**Comment by sp0nks** [comment]
CPU and RAM looks good but back to external screen not switching off.
Did I have to add the patches? If so, which one?

**Comment by vaxerski** [comment]
@gulafaran IIRC found a path where enabled state is not committed with dpms, that would require a hl patch, sec

**Comment by vaxerski** [comment]
actually

**Comment by gulafaran** [comment]
this also probably warrants for a fd leak check. so some explicit sync fds/timelines doesnt now suddenly end in limbo.

ls /proc/$(pidof Hyprland)/fd | wc -l

dpms a few times, run it again compare.

**Comment by vaxerski** [comment]
try this

**Comment by sp0nks** [comment]
Ok, give me a few minutes.

**Comment by sp0nks** [comment]
`ls /proc/$(pidof Hyprland)/fd | wc -l`
before 1st dpms off: 165
after: 165
and after 2nd dpms off: 157

On BTOP: CPU good and RAM good.

**Comment by gulafaran** [comment]
same here, works as intended so far.

**Comment by vaxerski** [comment]
good to merge then?

**Comment by gulafaran** [comment]
> good to merge then?

its not making things worse, and so far its making my 32 thread 157W laptop cpu not contribute to the climate heating when leaving it for a few minutes, you got my vote for merge.

**Comment by vaxerski** [comment]
lmao alright

**Comment by sp0nks** [comment]
Thank you!

**Comment by vaxerski** [comment]
yours truly

**Pull request merged**
