### PR TITLE
 Follow symlinks for AQ_DRM_DEVICES

### PR DESCRIPTION
**Pull request by sjcobb2022**
Addresses #33

Iterates over explicitly declared GPUs and canonicalizes paths. This has the additional include of `<filesystem>`
and `<system_error>`.

Currently does not check if the device is a valid drm KMS device. This could be added in the future.

Sorry for the messy git tree. Probably better to squash.

Note: This works for me, but additional testing would be greatly appreciated.

### CODE REVIEW

**Review by vaxerski — APPROVED** [review]
cool. We verify in a different place (if a device is not KMS, we wont accept it anyways) but an error would be nice yes

**Comment by sjcobb2022** [comment]
Alright, should I check for drnIsKms in this pull or a new one?

**Comment by vaxerski** [comment]
new one, I'll merge this. Sorry for my lack of respinsiveness I am in the middle of nowhere on a "kinda break"

**Comment by sjcobb2022** [comment]
> new one, I'll merge this. Sorry for my lack of respinsiveness I am in the middle of nowhere on a "kinda break"

Aw good for you. Have a nice one!

**Pull request merged**
