### PR TITLE
Nvidia fixes for scanout gbm allocation

### PR DESCRIPTION
**Pull request by vaxerski**
Nvidia cannot render to linear buffers part 2 the sequel

ref #26
ref https://github.com/hyprwm/Hyprland/issues/7005

needs testing

### CODE REVIEW

**Comment by vaxerski** [comment]
uhhh ci succeeds...

Also I still need confirmation whether this works

**Comment by vaxerski** [comment]
@fufexan fix

**Comment by vaxerski** [comment]
fixed

**Comment by vaxerski** [comment]
@fufexan fix ci

**Comment by fufexan** [comment]
not failing tho?

**Comment by vaxerski** [comment]
https://github.com/hyprwm/aquamarine/pull/27#issuecomment-2248200987

**Comment by fufexan** [comment]
So you want me to create a new workflow that builds hl main with current-rev aq?

**Comment by vaxerski** [comment]
on pr yes just liuke hl

**Comment by vaxerski** [comment]
the issue is the CI passed even tho the code from this branch wasnt compiling, so its not building this PR

**Comment by fufexan** [comment]
CI isn't lying, I've just built this on WSL.
```
[nixos@nixos:~]$ nix build github:hyprwm/aquamarine/fix-nv -L --extra-experimental-features 'nix-command flakes' --print-out-paths
/nix/store/xiaclrn5cggrmqbpb14afybi5ci7mi8r-aquamarine-0.1.0+date=2024-07-24_c63080e
```

**Comment by vaxerski** [comment]
jfc

last commit is fixed, you wont build dd8f3128a4bbab6d7bdfe132f1ee7a70bdc5ec46 though and it has a tick

**Comment by Agent00Ming** [comment]
this works for single nvidia gpu outputting through thunderbolt/usb-c to displayport, multigpu also works but this revealed that hotplug doesn't work for multigpu intel+nvidia (not a regression in this branch, it exists in main too)

**Comment by vaxerski** [comment]
ok mergging thennnn

**Comment by darkwater** [comment]
This breaks rendering on AMD graphics, I get a black screen

**Comment by vaxerski** [comment]
trace log please

**Comment by vaxerski** [comment]
@darkwater should be fixed in latest please check

**Comment by darkwater** [comment]
Nope, still broken

[hypr.log](https://github.com/user-attachments/files/16366680/hypr.log)

**Comment by vaxerski** [comment]
they aren't trace, but thanks.

**Comment by vaxerski** [comment]
lets move to #28

**Pull request merged**
